from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_DATA_DIR = PROJECT_ROOT / "data"
DEFAULT_CORPUS_DIR = DEFAULT_DATA_DIR / "corpus_poc2"
DEFAULT_INDEX_DIR = DEFAULT_CORPUS_DIR / "index"
DEFAULT_CACHE_DIR = DEFAULT_CORPUS_DIR / "cache"
DEFAULT_WORKLOADS_DIR = DEFAULT_DATA_DIR / "workloads"
DEFAULT_ARTIFACTS_DIR = PROJECT_ROOT / "artifacts"
DEFAULT_RUNS_DIR = DEFAULT_ARTIFACTS_DIR / "runs"
DEFAULT_EXPERIMENTS_DIR = PROJECT_ROOT / "experiments"


